function x = Optimization_Variable_Concatenation(Contact_Force_Array, Q_Qdot_Array, Control_Torque_Array, P)
% This function is used to pile up the variables to be optimized into a
% column vector

% Q_Qdot_Vec = Q_Qdot_Array;
% 
% Contact_Force_Vec = Contact_Force_Array;
% 
% Control_Torque_Vec = Control_Torque_Array;

Contact_Sequence = P.Contact_Sequence;

segment_number = length(Contact_Sequence); 

grids_per_segment = P.grids_per_segment;

x = [];

for i = 1:segment_number
    
    for j = 1:grids_per_segment
        
        current_index_ij  = (i-1) * (grids_per_segment) + j;

%         % Initialization of the state
%         eval(['syms ','rIx','_',num2str(i),'_',num2str(j),' rIy','_',num2str(i),'_',num2str(j),' theta','_',...
%            num2str(i),'_',num2str(j),' q1','_',num2str(i),'_',num2str(j),' q2','_',num2str(i),'_',num2str(j)...
%                      ,' q3','_',num2str(i),'_',num2str(j),' q4','_',num2str(i),'_',num2str(j),' q5','_',...
%                      num2str(i),'_',num2str(j),' q6','_',num2str(i),'_',num2str(j),' q7','_',num2str(i),...
%                      '_',num2str(j),' q8','_',num2str(i),'_',num2str(j),' q9','_',num2str(i),'_',num2str(j),...
%                      ' q10','_',num2str(i),'_',num2str(j),' real']);
% 
%         % Initialization of the statedot
%         eval(['syms ',' rIxdot','_',num2str(i),'_',num2str(j),' rIydot','_',num2str(i),'_',num2str(j),...
%                      ' thetadot','_',num2str(i),'_',num2str(j),' q1dot','_',num2str(i),'_',num2str(j),...
%                      ' q2dot','_',num2str(i),'_',num2str(j) ,' q3dot','_',num2str(i),'_',num2str(j),....
%                      ' q4dot','_',num2str(i),'_',num2str(j),' q5dot','_',num2str(i),'_',num2str(j),...
%                      ' q6dot','_',num2str(i),'_',num2str(j),' q7dot','_',num2str(i),'_',num2str(j)...
%                      ,' q8dot','_',num2str(i),'_',num2str(j),' q9dot','_',num2str(i),'_',num2str(j),...
%                      ' q10dot','_',num2str(i),'_',num2str(j),' real']);
                 
        x = [x; Q_Qdot_Array(:,current_index_ij)];
        

%         % Initialization of the lamda
%         eval(['syms ',' lamda_Ax','_',num2str(i),'_',num2str(j),' lamda_Ay','_',num2str(i),'_',num2str(j),...
%             ' lamda_Bx','_',num2str(i),'_',num2str(j),' lamda_By','_',num2str(i),'_',num2str(j),...
%             ' lamda_Cx','_',num2str(i),'_',num2str(j),' lamda_Cy','_',num2str(i),'_',num2str(j),...
%             ' lamda_Dx','_',num2str(i),'_',num2str(j),' lamda_Dy','_',num2str(i),'_',num2str(j),...
%             ' lamda_Mx','_',num2str(i),'_',num2str(j),' lamda_My','_',num2str(i),'_',num2str(j),...
%             ' lamda_Ox','_',num2str(i),'_',num2str(j),' lamda_Oy','_',num2str(i),'_',num2str(j),...
%             ' real']);
        x = [x; Contact_Force_Array(:,current_index_ij)];

%         % Initialization of the control
%         eval(['syms ',' u1','_',num2str(i),'_',num2str(j),' u2','_',num2str(i),'_',num2str(j),...
%                       ' u3','_',num2str(i),'_',num2str(j),' u4','_',num2str(i),'_',num2str(j),...
%                       ' u5','_',num2str(i),'_',num2str(j),' u6','_',num2str(i),'_',num2str(j),...
%                       ' u7','_',num2str(i),'_',num2str(j),' u8','_',num2str(i),'_',num2str(j),...
%                       ' u9','_',num2str(i),'_',num2str(j),' u10','_',num2str(i),'_',num2str(j),' real']);
                  
         x = [x; Control_Torque_Array(:,current_index_ij)];
                 
    end
    if i<segment_number     
%         eval(['syms ',' lambar_Ax','_',num2str(i),' lambar_Ay','_',num2str(i),...
%             ' lambar_Bx','_',num2str(i),' lambar_By','_',num2str(i),...
%             ' lambar_Cx','_',num2str(i),' lambar_Cy','_',num2str(i),...
%             ' lambar_Dx','_',num2str(i),' lambar_Dy','_',num2str(i),...
%             ' lambar_Mx','_',num2str(i),' lambar_My','_',num2str(i),...
%             ' lambar_Ox','_',num2str(i),' lambar_Oy','_',num2str(i),...
%             ' real']);
        x = [x; Contact_Force_Array(:,current_index_ij)];
    end
end


fileID = fopen('snopt_init.txt','wt');
for i = 1:length(x)
    fprintf(fileID,'%f ', x(i));
    fprintf(fileID,'\n');
end
fclose(fileID);
end